<a href="https://colab.research.google.com/github/maydayannie/PyTorch_Deeplearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)


2.6.0+cu124


# Introduction to Tensors
Creating tensors
PyTorch tensors are created using torch.Tensor()= https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim


1

In [9]:
vector.shape

torch.Size([2])

In [14]:
# Matrix
Matrix = torch.tensor([[7, 8, 9],
                       [9, 10,11]])
Matrix

tensor([[ 7,  8,  9],
        [ 9, 10, 11]])

In [15]:
Matrix.ndim

2

In [16]:
Matrix.shape

torch.Size([2, 3])

In [18]:
Matrix[0]

tensor([7, 8, 9])

In [31]:
# Tensor
Tensor = torch.tensor([
    [[1, 0, 0],
     [2, 5, 5],
     [3, 6, 6]],
    [[1, 2, 3],
     [3, 6, 9],
     [2, 4, 5]]
    ])
Tensor

tensor([[[1, 0, 0],
         [2, 5, 5],
         [3, 6, 6]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [27]:
Tensor.ndim

3

In [28]:
Tensor.shape

torch.Size([2, 3, 3])

In [36]:
Tensor[0]

tensor([[1, 0, 0],
        [2, 5, 5],
        [3, 6, 6]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers



